api.poscare.ru/routes/web.php
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'Admin\HomeController@index')->name('home');

    Route::prefix('user')->group(function () {
        /* HomeController. returns views */
        Route::get('/', 'Admin\HomeController@getUsers');
        Route::get('/get/{id}', 'Admin\HomeController@getUser');
        Route::get('/get/{user_id}/branch/new', 'Admin\HomeController@userBranchCreate');
        Route::get('/get/branch/{branch_id}/edit', 'Admin\HomeController@userBranchEdit');
        Route::get('/new', 'Admin\HomeController@newUser');
        Route::post('/new', 'Admin\HomeController@saveNewUser');
        /* AdminController. returns json */
        Route::post('/list', 'Admin\AdminController@userList');
        Route::post('/save', 'Admin\AdminController@saveUser');
        Route::post('/delete', 'Admin\AdminController@deleteUser');
        Route::post('/opt/create', 'Admin\AdminController@userOptCreate');
        Route::post('/opt/edit', 'Admin\AdminController@userOptEdit');
        Route::post('/branch/edit', 'Admin\AdminController@branchEdit');
        Route::post('/branch/create', 'Admin\AdminController@branchCreate');
        Route::post('/branch/image/add', 'Admin\AdminController@branchImageAdd');
        Route::post('/branch/image/delete', 'Admin\AdminController@branchImageDelete');
        Route::post('/branch/{branch_id}/delete', 'Admin\AdminController@userBranchDelete');
        Route::post('/service/verify', 'Admin\AdminController@userServiceVerify');


        Route::post('/rewards/force', 'Admin\RewardController@force');

    });
    Route::prefix('lists')->group(function () {
        // Route::get('/', 'Admin\AdminController@getLists');
        Route::get('/{vue_capture?}', function () {
            return view('lists');
        })->where('vue-capture', '[\/w\.-]*');
        Route::post('/categories', 'Admin\AdminController@getCategories');
        Route::post('/categories/order', 'Admin\AdminController@orderCategory');
        Route::post('/category/delete', 'Admin\AdminController@deleteCategory');
        Route::post('/category/create', 'Admin\AdminController@createCategory');
        Route::post('/category/edit', 'Admin\AdminController@editCategory');

        Route::post('/products', 'Admin\AdminController@getProducts');
        Route::post('/products/import', 'Admin\AdminController@importProducts');
        Route::get('/products/export', 'Admin\AdminController@exportProducts');
        Route::post('/products/order', 'Admin\AdminController@orderProducts');
        Route::post('/product/delete', 'Admin\AdminController@deleteProduct');
        Route::get('/product/create', 'Admin\AdminController@newProductPage');
        Route::post('/product/create', 'Admin\AdminController@newProduct');
        Route::get('/product/edit/{id}', 'Admin\AdminController@editProductPage');
        Route::post('/product/edit', 'Admin\AdminController@editProduct');

        Route::post('/services', 'Admin\AdminController@getServices');
        Route::post('/services/order', 'Admin\AdminController@orderServices');
        Route::get('/service/create', 'Admin\AdminController@createServicePage');
        Route::post('/service/create', 'Admin\AdminController@createService');
        Route::get('/service/edit/{id}', 'Admin\AdminController@editServicePage');
        Route::post('/service/edit', 'Admin\AdminController@editService');
        Route::post('/service/delete', 'Admin\AdminController@deleteService');

        Route::post('/characters', 'Admin\AdminController@getCharacters');
        Route::post('/characters/order', 'Admin\AdminController@orderCharacters');
        Route::post('/character/delete', 'Admin\AdminController@deleteCharacter');
        Route::post('/character/edit', 'Admin\AdminController@editCharacter');
        Route::post('/character/create', 'Admin\AdminController@createCharacter');

        Route::post('/related_services', 'Admin\AdminController@getRelatedServices');
        Route::post('/related_services/order', 'Admin\AdminController@orderRelatedServices');
        Route::post('/related_service/create', 'Admin\AdminController@createRelatedService');
        Route::post('/related_service/delete', 'Admin\AdminController@deleteRelatedService');
        Route::post('/related_service/edit', 'Admin\AdminController@editRelatedService');

        Route::post('/deliveries', 'Admin\AdminController@getDeliveries');
        Route::post('/deliveries/order', 'Admin\AdminController@orderDeliveries');
        Route::post('/delivery/delete', 'Admin\AdminController@deleteDelivery');
        Route::post('/delivery/edit', 'Admin\AdminController@editDelivery');
        Route::post('/delivery/create', 'Admin\AdminController@createDelivery');

        Route::post('/payments', 'Admin\AdminController@getPayments');
        Route::post('/payments/order', 'Admin\AdminController@orderPayments');
        Route::post('/payment/delete', 'Admin\AdminController@deletePayment');
        Route::post('/payment/edit', 'Admin\AdminController@editPayment');
        Route::post('/payment/create', 'Admin\AdminController@createPayment');

        Route::post('/rewards', 'Admin\RewardController@getRewards');
        Route::post('/reward/delete', 'Admin\RewardController@deleteReward');
        Route::get('/reward/edit/{id}', 'Admin\RewardController@editRewardPage');
        Route::post('/reward/edit', 'Admin\RewardController@editReward');
        Route::get('/reward/create', 'Admin\RewardController@createRewardPage');
        Route::post('/reward/create', 'Admin\RewardController@createReward');
    });
    Route::prefix('moderation')->group(function () {
        Route::get('/', 'Admin\AdminController@getModeration');

        Route::post('/bids', 'Admin\AdminController@bidsToModerate');
        Route::post('/bid/accept', 'Admin\AdminController@acceptBid');
        Route::post('/bid/reject', 'Admin\AdminController@rejectBid');
        Route::get('/bid/offer/{id}', 'Admin\AdminController@bidOfferPage');
        Route::post('/bid/offer', 'Admin\AdminController@bidOffer');

        Route::post('/orders', 'Admin\AdminController@ordersToModerate');
        Route::post('/order/accept', 'Admin\AdminController@acceptOrder');
        Route::post('/order/reject', 'Admin\AdminController@rejectOrder');
        Route::get('/order/offer/{id}', 'Admin\AdminController@orderOfferPage');
        Route::post('/order/offer', 'Admin\AdminController@orderOffer');

        Route::post('/reviews', 'Admin\AdminController@reviewsToModerate');
        Route::post('/review/accept', 'Admin\AdminController@acceptReview');
        Route::post('/review/reject', 'Admin\AdminController@rejectReview');

        Route::post('/images', 'Admin\AdminController@imagesToModerate');
        Route::post('/image/accept', 'Admin\AdminController@acceptImage');
        Route::post('/image/reject', 'Admin\AdminController@rejectImage');

	    Route::post('/tenders', 'Admin\TenderController@tendersToModerate');
	    Route::post('/tender/accept', 'Admin\TenderController@acceptTender');
	    Route::post('/tender/reject', 'Admin\TenderController@rejectTender');
    });
    Route::prefix('bids')->group(function () {
        Route::get('/', 'Admin\AdminController@getBidsPage');
        Route::post('/list', 'Admin\AdminController@getBids');
        Route::get('/new', 'Admin\AdminController@newBid');

        Route::get('/getOne/{id}', 'Admin\AdminController@getBid');
        Route::post('/getOne/edit', 'Admin\AdminController@editBid');
    });
    Route::prefix('orders')->group(function () {
        Route::get('/', 'Admin\AdminController@getOrdersPage');
        Route::post('/list', 'Admin\AdminController@getOrders');
        Route::get('/new', 'Admin\AdminController@newOrder');

        Route::get('/getOne/{id}', 'Admin\AdminController@getOrder');
        Route::post('/getOne/edit', 'Admin\AdminController@editOrder');
    });

    Route::prefix('tenders')->group(function () {
        Route::get('/', 'Admin\TenderController@list');
        Route::get('create', 'Admin\TenderController@create');
        Route::post('store', 'Admin\TenderController@store');
        Route::get('/{id}', 'Admin\TenderController@show');
        Route::get('{id}/edit', 'Admin\TenderController@edit');
        Route::post('update', 'Admin\TenderController@update');
        Route::post('delete', 'Admin\TenderController@delete');

        Route::prefix('response')->group(function () {
            //Route::get('list', 'Admin\TenderResponseController@list');
            //Route::get('show', 'Admin\TenderResponseController@show');
            //Route::post('create', 'Admin\TenderResponseController@create');
            //Route::post('edit', 'Admin\TenderResponseController@edit');
            Route::post('delete', 'Admin\TenderController@deleteResponse');
        });
    });

    Route::prefix('news')->group(function () {
        Route::get('/', 'Admin\AdminController@getNewsPage');
        Route::get('/get/{id}', 'Admin\AdminController@getNews');
        Route::get('/create', 'Admin\AdminController@createNewsPage');
        Route::post('/create', 'Admin\AdminController@createNews');
        Route::post('/edit', 'Admin\AdminController@editNews');
        Route::post('/delete', 'Admin\AdminController@deleteNews');
    });
    Route::prefix('sales')->group(function () {
        Route::get('/', 'Admin\AdminController@getSalesPage');
        Route::get('/get/{id}', 'Admin\AdminController@getSale');
        Route::get('/create', 'Admin\AdminController@createSalePage');
        Route::post('/create', 'Admin\AdminController@createSale');
        Route::post('/edit', 'Admin\AdminController@editSale');
        Route::post('/delete', 'Admin\AdminController@deleteSale');
    });
    Route::resource('settings', 'Admin\SettingsController');
});

Route::any('/getcities', 'Admin\AdminController@getCities');

api.poscare.ru/app/Models/Tender.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Tender extends Model
{
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function tenderResponses()
    {
        return $this->hasMany('App\Models\TenderResponse');
    }

    public function branch()
    {
        return $this->belongsTo('App\Models\Branch');
    }

    public function products()
    {
        return $this->belongsToMany('App\Models\Product',
            'product_tender')->withPivot('quantity')->withPivot('price')->withTimestamps();
    }

    public function getTermsAttribute($value)
    {
        if (!$value) {
            return null;
        }

        return Carbon::parse($value)->timestamp;
    }

    /*public function setTermsAttribute($value)
    {
        if (!$value) {
            $this->attributes['terms'] = null;
        }
        $this->attributes['terms'] = Carbon::createFromTimestamp($value)->format('Y-m-d H:i:s');
    }*/

    public function getCreatedAtAttribute($value)
    {
        if (!$value) {
            return null;
        }

        return Carbon::parse($value)->timestamp;
    }

    public function getUpdatedAtAttribute($value)
    {
        if (!$value) {
            return null;
        }

        return Carbon::parse($value)->timestamp;
    }

    /**
     * Список тендеров
     *
     * Статусы:
     *
     *  is_mine = 0
     *  null - все, кроме модерации
     *  0 - модерация
     *  1 - (didIAnswer = 0) - Новый
     *  1 - (didIAnswer = 1) - Участник
     *  2 - Исполнитель
     *  3 - Закрыт
     *  4 - Архив
     *
     */

    public function getGetStatusAttribute()
    {
        $status = $this->status;
        if ($status == 1) {
            return "Новый";
        } elseif ($status == 2) {
            return "Выбран исполнитель";
        } elseif ($status == 3) {
            return "Закрыт";
        } elseif ($status == 4) {
            return "В архиве";
        } else {
            return "Модерация";
        }
    }

    public function getGetModerationAttribute()
    {
        $is_accepted = $this->is_accepted;
        if ($is_accepted == 1) {
            return "Одобрено";
        } elseif ($is_accepted == 2) {
            return "Отклонено";
        } else {
            return "Новое";
        }
    }

    public function getGetPrivateAttribute()
    {
        $is_private = $this->is_private;
        return $is_private?"Приватный":"Общий";
    }

}

api.poscare.ru/app/Http/Controllers/Admin/TenderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Classes\ApiError;
use App\Models\Product;
use App\Models\Tender;
use App\Models\TenderResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class TenderController extends Controller {
	public function list() {
		$tenders = Tender::orderBy( 'created_at', 'desc' )->get();

		return view( 'tenders.list', compact( 'tenders' ) );
	}

	public function create() {
		$products = Product::all();

		return view( 'tenders.create', compact( 'products' ) );
	}

	public function store( Request $request ) {
		$tender              = new Tender;
		$tender->terms       = $request->terms;
		$tender->status      = $request->status;
		$tender->is_accepted = $request->is_accepted;
		$tender->description = $request->description;
		$tender->is_private  = $request->is_private;
		$tender->user_id     = Auth::id();
		$tender->save();

		$products = $request->products;
		$tender->products()->detach();
		if ( $products ) {
			foreach ( $products as $key => $product ) {
				if ( ! $product['quantity'] ) {
					continue;
				}
				$tender->products()->attach( $key, [
					'quantity' => $product['quantity'],
					'price' => isset( $product['price'] ) ? $product['price'] : null
				] );
			}
		}


		return redirect( '/tenders/' . $tender->id );
	}

	public function show( $id ) {
		$tender = Tender::findOrFail( $id );

		return view( 'tenders.show', compact( 'tender' ) );
	}

	public function edit( $id ) {
		$tender = Tender::findOrFail( $id );

		$products = Product::all();

		$tenderProducts = $tender->products()->get();

		return view( 'tenders.edit', compact( 'tender', 'products', 'tenderProducts' ) );
	}

	public function update( Request $request ) {
		$tender              = Tender::findOrFail( $request->tender_id );
		$tender->terms       = $request->terms;
		$tender->status      = $request->status;
		$tender->is_accepted = $request->is_accepted;
		$tender->description = $request->description;
		$tender->is_private  = $request->is_private;
		$tender->save();

		$products = $request->products;
		$tender->products()->detach();
		if ( $products ) {
			foreach ( $products as $key => $product ) {
				if ( ! $product['quantity'] ) {
					continue;
				}
				$tender->products()->attach( $key, [
					'quantity' => $product['quantity'],
					'price' => isset( $product['price'] ) ? $product['price'] : null
				] );
			}
		}


		return redirect( '/tenders/' . $tender->id );
	}

	public function delete( Request $request ) {
		$tender = Tender::findOrFail( $request->tender_id );
		$tender->delete();

		return redirect( '/tenders/' );
	}

	public function deleteResponse( Request $request ) {

		$response = TenderResponse::findOrFail( $request->tender_response_id );
		$tender   = $response->tender;
		$response->delete();

		return redirect( '/tenders/' . $tender->id );
	}

	public function tendersToModerate( Request $request ) {
		$tenders = Tender::where( 'status', 0 )->with( 'user', 'products', 'user.city' )->get();
		return $tenders;
	}

	public function acceptTender( Request $request ) {
		$validator = Validator::make( $request->all(), [
			'tender_id' => 'required|integer',
		] );
		if ( $validator->fails() ) {

			$val_err = $validator->errors();

			$err = new ApiError( 299, null, null, $val_err->all() );

			return $err->json();

		}

		$tender = Tender::findOrFail( $request->tender_id );
		if ( $tender->status < 1 ) {
			$tender->status      = 1;
			$tender->is_accepted = 1;
			$tender->save();
		}

		return response()->json( [

			'response' => 1,

		], 200, [], JSON_UNESCAPED_UNICODE );
	}

	public function rejectTender( Request $request ) {
		$validator = Validator::make( $request->all(), [
			'tender_id' => 'required|integer',
		] );
		if ( $validator->fails() ) {

			$val_err = $validator->errors();

			$err = new ApiError( 299, null, null, $val_err->all() );

			return $err->json();

		}

		$tender = Tender::findOrFail( $request->tender_id );
		if ( $tender->status < 1 ) {
			$tender->status      = 1;
			$tender->is_accepted = 2;
			$tender->save();
		}

		return response()->json( [

			'response' => 1,

		], 200, [], JSON_UNESCAPED_UNICODE );
	}
}

api.poscare.ru/resources/views/tenders/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <ol class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li class="active">Тендеры</li>
                </ol>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Тендеры
                        <a class="btn btn-info btn-xs pull-right" href="{{url('/tenders/create')}}">Создать тендер</a>
                    </div>

                    <div class="panel-body" id="get-tenders">
                        @if($tenders->count()>0)
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Создатель</td>
                                        <td>Срок</td>
                                        <td>Статус</td>
                                        <td>Модерация</td>
                                        <td>Описание</td>
                                        <td>Приват</td>
                                        <td>Победитель</td>
                                        <td></td>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($tenders as $tender)
                                        <tr>
                                            <td>
                                                <a href="/tenders/{{$tender->id}}">
                                                    {{$tender->id}}
                                                </a>
                                            </td>
                                            <td>
                                                {{$tender->user->name}}
                                            </td>
                                            <td>
                                                <a href="/tenders/{{$tender->id}}">
                                                    {{\Carbon\Carbon::createFromTimestamp($tender->terms)->format('d.m.Y H:i')}}
                                                </a>
                                            </td>
                                            <td>
                                                <a href="/tenders/{{$tender->id}}">
                                                    {{$tender->get_status}}
                                                </a>
                                            </td>
                                            <td>
                                                <a href="/tenders/{{$tender->id}}">
                                                    {{$tender->get_moderation}}
                                                </a>
                                            </td>
                                            <td>
                                                <a href="/tenders/{{$tender->id}}">
                                                    {{$tender->description}}
                                                </a>
                                            </td>
                                            <td>
                                                <a href="/tenders/{{$tender->id}}">
                                                    {{$tender->get_private}}
                                                </a>
                                            </td>
                                            <td>
                                                {{$tender->branch?$tender->branch->user->name:'Не определен'}}
                                            </td>
                                            <td>
                                                <form action="/tenders/delete" method="post">
                                                    {{csrf_field()}}
                                                    <input type="hidden" name="tender_id" value="{{$tender->id}}">
                                                    <button class="btn btn-xs btn-danger" type="submit">
                                                        <span class="glyphicon glyphicon-trash"></span>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        @else
                            <div class="alert alert-info">Тендеры еще не созданы</div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

api.poscare.ru/resources/views/tenders/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <ol class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li class="active">Тендеры</li>
                </ol>
                <div class="panel panel-default">
                    <div class="panel-heading">

                        <a href="/tenders/{{$tender->id}}/edit" class="btn btn-default btn-xs pull-right">
                            Редактировать
                        </a>
                        Тендер {{$tender->id}}
                    </div>

                    <div class="panel-body" id="get-tenders">
                        <h4>Информация</h4>
                        {{$tender->description}}
                        <ul>
                            <li>
                                ID <strong>{{$tender->id}}</strong>
                            </li>
                            <li>
                                Создатель
                                <strong>
                                    @if($tender->user)
                                        <a href="{{url('/user/get/'.$tender->user->id)}}">{{$tender->user->name}}</a>
                                    @else
                                        Пользователь не определён
                                    @endif
                                </strong>

                            </li>
                            <li>
                                Срок:
                                <strong>{{\Carbon\Carbon::createFromTimestamp($tender->terms)->format('d.m.Y H:i')}}</strong>
                            </li>
                            <li>
                                Статус: <strong>{{$tender->get_status}}</strong>
                            </li>
                            <li>
                                Модерация: <strong>{{$tender->get_moderation}}</strong>
                            </li>
                            <li>
                                Приват: <strong>{{$tender->get_private}}</strong>
                            </li>
                            <li>
                                Победитель:
                                <strong>{{$tender->branch?$tender->branch->user->name:'Не определен'}}</strong>
                            </li>
                        </ul>
                        <hr>
                        <h4>Товары</h4>
                        @if($tender->products->count()>0)
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <tbody>
                                    @foreach($tender->products()->get() as $product)
                                        <tr>
                                            <td>{{$product->name}}</td>
                                            <td>{{$product->pivot->quantity}} шт.</td>
                                            <td>{{$product->pivot->price}} руб.</td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        @else
                            <p><strong>К тендеру не прикреплены товары</strong></p>
                        @endif
                        <hr>
                        <h4>Ответы</h4>
                        @if($tender->tenderResponses->count()>0)
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Создатель</td>
                                        <td>Цена</td>
                                        <td>Время</td>
                                        <td>Комментарий</td>
                                        <td></td>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($tender->tenderResponses as $response)
                                        <tr>
                                            <td>
                                                {{$response->id}}
                                            </td>
                                            <td>
                                                {{$response->branch->user->name}}
                                            </td>
                                            <td>
                                                {{$response->price}}
                                            </td>
                                            <td>
                                                {{$response->time_value}} {{$response->human_time_key}}
                                            </td>
                                            <td>
                                                {{$response->comment}}
                                            </td>
                                            <td>
                                                <form action="/tenders/response/delete" method="post">
                                                    {{csrf_field()}}
                                                    <input type="hidden" name="tender_response_id"
                                                           value="{{$response->id}}">
                                                    <button class="btn btn-xs btn-danger" type="submit">
                                                        <span class="glyphicon glyphicon-trash"></span>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        @else
                            <div class="alert alert-info">Ответы еще не созданы</div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection