api.poscare.ru/routes/web.php
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'Admin\HomeController@index')->name('home');

    Route::prefix('user')->group(function () {
        /* HomeController. returns views */
        Route::get('/', 'Admin\HomeController@getUsers');
        Route::get('/get/{id}', 'Admin\HomeController@getUser');
        Route::get('/get/{user_id}/branch/new', 'Admin\HomeController@userBranchCreate');
        Route::get('/get/branch/{branch_id}/edit', 'Admin\HomeController@userBranchEdit');
        Route::get('/new', 'Admin\HomeController@newUser');
        Route::post('/new', 'Admin\HomeController@saveNewUser');
        /* AdminController. returns json */
        Route::post('/list', 'Admin\AdminController@userList');
        Route::post('/save', 'Admin\AdminController@saveUser');
        Route::post('/delete', 'Admin\AdminController@deleteUser');
        Route::post('/opt/create', 'Admin\AdminController@userOptCreate');
        Route::post('/opt/edit', 'Admin\AdminController@userOptEdit');
        Route::post('/branch/edit', 'Admin\AdminController@branchEdit');
        Route::post('/branch/create', 'Admin\AdminController@branchCreate');
        Route::post('/branch/image/add', 'Admin\AdminController@branchImageAdd');
        Route::post('/branch/image/delete', 'Admin\AdminController@branchImageDelete');
        Route::post('/branch/{branch_id}/delete', 'Admin\AdminController@userBranchDelete');
        Route::post('/service/verify', 'Admin\AdminController@userServiceVerify');


        Route::post('/rewards/force', 'Admin\RewardController@force');

    });
    Route::prefix('lists')->group(function () {
        // Route::get('/', 'Admin\AdminController@getLists');
        Route::get('/{vue_capture?}', function () {
            return view('lists');
        })->where('vue-capture', '[\/w\.-]*');
        Route::post('/categories', 'Admin\AdminController@getCategories');
        Route::post('/categories/order', 'Admin\AdminController@orderCategory');
        Route::post('/category/delete', 'Admin\AdminController@deleteCategory');
        Route::post('/category/create', 'Admin\AdminController@createCategory');
        Route::post('/category/edit', 'Admin\AdminController@editCategory');

        Route::post('/products', 'Admin\AdminController@getProducts');
        Route::post('/products/import', 'Admin\AdminController@importProducts');
        Route::get('/products/export', 'Admin\AdminController@exportProducts');
        Route::post('/products/order', 'Admin\AdminController@orderProducts');
        Route::post('/product/delete', 'Admin\AdminController@deleteProduct');
        Route::get('/product/create', 'Admin\AdminController@newProductPage');
        Route::post('/product/create', 'Admin\AdminController@newProduct');
        Route::get('/product/edit/{id}', 'Admin\AdminController@editProductPage');
        Route::post('/product/edit', 'Admin\AdminController@editProduct');

        Route::post('/services', 'Admin\AdminController@getServices');
        Route::post('/services/order', 'Admin\AdminController@orderServices');
        Route::get('/service/create', 'Admin\AdminController@createServicePage');
        Route::post('/service/create', 'Admin\AdminController@createService');
        Route::get('/service/edit/{id}', 'Admin\AdminController@editServicePage');
        Route::post('/service/edit', 'Admin\AdminController@editService');
        Route::post('/service/delete', 'Admin\AdminController@deleteService');

        Route::post('/characters', 'Admin\AdminController@getCharacters');
        Route::post('/characters/order', 'Admin\AdminController@orderCharacters');
        Route::post('/character/delete', 'Admin\AdminController@deleteCharacter');
        Route::post('/character/edit', 'Admin\AdminController@editCharacter');
        Route::post('/character/create', 'Admin\AdminController@createCharacter');

        Route::post('/related_services', 'Admin\AdminController@getRelatedServices');
        Route::post('/related_services/order', 'Admin\AdminController@orderRelatedServices');
        Route::post('/related_service/create', 'Admin\AdminController@createRelatedService');
        Route::post('/related_service/delete', 'Admin\AdminController@deleteRelatedService');
        Route::post('/related_service/edit', 'Admin\AdminController@editRelatedService');

        Route::post('/deliveries', 'Admin\AdminController@getDeliveries');
        Route::post('/deliveries/order', 'Admin\AdminController@orderDeliveries');
        Route::post('/delivery/delete', 'Admin\AdminController@deleteDelivery');
        Route::post('/delivery/edit', 'Admin\AdminController@editDelivery');
        Route::post('/delivery/create', 'Admin\AdminController@createDelivery');

        Route::post('/payments', 'Admin\AdminController@getPayments');
        Route::post('/payments/order', 'Admin\AdminController@orderPayments');
        Route::post('/payment/delete', 'Admin\AdminController@deletePayment');
        Route::post('/payment/edit', 'Admin\AdminController@editPayment');
        Route::post('/payment/create', 'Admin\AdminController@createPayment');

        Route::post('/rewards', 'Admin\RewardController@getRewards');
        Route::post('/reward/delete', 'Admin\RewardController@deleteReward');
        Route::get('/reward/edit/{id}', 'Admin\RewardController@editRewardPage');
        Route::post('/reward/edit', 'Admin\RewardController@editReward');
        Route::get('/reward/create', 'Admin\RewardController@createRewardPage');
        Route::post('/reward/create', 'Admin\RewardController@createReward');
    });
    Route::prefix('moderation')->group(function () {
        Route::get('/', 'Admin\AdminController@getModeration');

        Route::post('/bids', 'Admin\AdminController@bidsToModerate');
        Route::post('/bid/accept', 'Admin\AdminController@acceptBid');
        Route::post('/bid/reject', 'Admin\AdminController@rejectBid');
        Route::get('/bid/offer/{id}', 'Admin\AdminController@bidOfferPage');
        Route::post('/bid/offer', 'Admin\AdminController@bidOffer');

        Route::post('/orders', 'Admin\AdminController@ordersToModerate');
        Route::post('/order/accept', 'Admin\AdminController@acceptOrder');
        Route::post('/order/reject', 'Admin\AdminController@rejectOrder');
        Route::get('/order/offer/{id}', 'Admin\AdminController@orderOfferPage');
        Route::post('/order/offer', 'Admin\AdminController@orderOffer');

        Route::post('/reviews', 'Admin\AdminController@reviewsToModerate');
        Route::post('/review/accept', 'Admin\AdminController@acceptReview');
        Route::post('/review/reject', 'Admin\AdminController@rejectReview');

        Route::post('/images', 'Admin\AdminController@imagesToModerate');
        Route::post('/image/accept', 'Admin\AdminController@acceptImage');
        Route::post('/image/reject', 'Admin\AdminController@rejectImage');

	    Route::post('/tenders', 'Admin\TenderController@tendersToModerate');
	    Route::post('/tender/accept', 'Admin\TenderController@acceptTender');
	    Route::post('/tender/reject', 'Admin\TenderController@rejectTender');
    });
    Route::prefix('bids')->group(function () {
        Route::get('/', 'Admin\AdminController@getBidsPage');
        Route::post('/list', 'Admin\AdminController@getBids');
        Route::get('/new', 'Admin\AdminController@newBid');

        Route::get('/getOne/{id}', 'Admin\AdminController@getBid');
        Route::post('/getOne/edit', 'Admin\AdminController@editBid');
    });
    Route::prefix('orders')->group(function () {
        Route::get('/', 'Admin\AdminController@getOrdersPage');
        Route::post('/list', 'Admin\AdminController@getOrders');
        Route::get('/new', 'Admin\AdminController@newOrder');

        Route::get('/getOne/{id}', 'Admin\AdminController@getOrder');
        Route::post('/getOne/edit', 'Admin\AdminController@editOrder');
    });

    Route::prefix('tenders')->group(function () {
        Route::get('/', 'Admin\TenderController@list');
        Route::get('create', 'Admin\TenderController@create');
        Route::post('store', 'Admin\TenderController@store');
        Route::get('/{id}', 'Admin\TenderController@show');
        Route::get('{id}/edit', 'Admin\TenderController@edit');
        Route::post('update', 'Admin\TenderController@update');
        Route::post('delete', 'Admin\TenderController@delete');

        Route::prefix('response')->group(function () {
            //Route::get('list', 'Admin\TenderResponseController@list');
            //Route::get('show', 'Admin\TenderResponseController@show');
            //Route::post('create', 'Admin\TenderResponseController@create');
            //Route::post('edit', 'Admin\TenderResponseController@edit');
            Route::post('delete', 'Admin\TenderController@deleteResponse');
        });
    });

    Route::prefix('news')->group(function () {
        Route::get('/', 'Admin\AdminController@getNewsPage');
        Route::get('/get/{id}', 'Admin\AdminController@getNews');
        Route::get('/create', 'Admin\AdminController@createNewsPage');
        Route::post('/create', 'Admin\AdminController@createNews');
        Route::post('/edit', 'Admin\AdminController@editNews');
        Route::post('/delete', 'Admin\AdminController@deleteNews');
    });
    Route::prefix('sales')->group(function () {
        Route::get('/', 'Admin\AdminController@getSalesPage');
        Route::get('/get/{id}', 'Admin\AdminController@getSale');
        Route::get('/create', 'Admin\AdminController@createSalePage');
        Route::post('/create', 'Admin\AdminController@createSale');
        Route::post('/edit', 'Admin\AdminController@editSale');
        Route::post('/delete', 'Admin\AdminController@deleteSale');
    });
    Route::resource('settings', 'Admin\SettingsController');
});

Route::any('/getcities', 'Admin\AdminController@getCities');

api.poscare.ru/app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    public function getBotSettingsAttribute($value)
    {
        return json_decode($value);
    }

    public function setBotSettingsAttribute($value)
    {
        if ($value != null) {
            $this->attributes['bot_settings'] = json_encode($value);
        } else {
            $this->attributes['bot_settings'] = null;
        }
    }
}

api.poscare.ru/app/Http/Controllers/Admin/SettingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\RatingEvent;
use App\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SettingsController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$settings = Setting::first();
		$ratings  = RatingEvent::all();
		return view( 'settings.settings', compact( 'settings', 'ratings' ) );
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store( Request $request ) {

		$settings = Setting::find( 1 );

		$botSettings = [];
		if ( ! $settings ) {
			$settings = new Setting();
		} else {
			$botSettings = $settings->bot_settings;
		}
		$botSettings['bid_answer']   = $request->bid_answer;
		$botSettings['order_answer'] = $request->order_answer;
		$botSettings['bot_timeout']  = explode( ':', $request->bot_timeout )[0] * 60 + explode( ':', $request->bot_timeout )[1];
		$settings->bot_settings      = $botSettings;

		$settings->save();

		$ratings = $request->ratings;
		foreach ( $ratings as $key => $value ) {
			$rating = RatingEvent::find( $key );
			if ( $rating ) {
				$rating->score = $value;
				$rating->save();
			}
		}

		return back();

	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show( $id ) {
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( $id ) {
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( Request $request, $id ) {


		$settings = Setting::first();
		if ( $request->settings == 'bot' ) {
			$botSettings                 = [];
			$botSettings['bid_answer']   = $request->bid_answer;
			$botSettings['order_answer'] = $request->order_answer;
			$botSettings['bot_timeout']  = explode( ':', $request->bot_timeout )[0] * 60 + explode( ':', $request->bot_timeout )[1];
			$settings->bot_settings      = $botSettings;
		}
		$settings->save();

		return back();
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( $id ) {
		//
	}
}

api.poscare.ru/resources/views/settings/settings.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Настройки</div>

                    <div class="panel-body" id="settings">
                        <h4>Настройки бота</h4>
                        <div class="alert alert-info">
                            Подсказка
                            <ul>
                                <li>Текст ответа заявки</li>
                                <li>Текст ответа заказа</li>
                                <li>Время срабатывания</li>
                                <li>Среднее время поставки (Кол-во и Час, День, Месяц)</li>
                            </ul>
                        </div>
                        <form role="form" action="{{route('settings.store')}}" method="post">
                            {{csrf_field()}}
                            <input type="hidden" name="settings" value="bot">
                            <div class="form-group">
                                <label for="bid_answer" class="col-sm-3">Ответ на заявку</label>
                                <div class="col-sm-9">
                                    <input type="text" name="bid_answer" id="bid_answer" class="form-control"
                                           value="{{$settings&&$settings->bot_settings?$settings->bot_settings->bid_answer:''}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="order_answer" class="col-sm-3">Ответ на заказ</label>
                                <div class="col-sm-9">
                                    <input type="text" name="order_answer" id="order_answer" class="form-control"
                                           value="{{$settings&&$settings->bot_settings?$settings->bot_settings->order_answer:''}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="bot_timeout" class="col-sm-3">Время срабатывания</label>
                                <div class="col-sm-9">
                                    <input type="time" name="bot_timeout" id="bot_timeout" class="form-control"
                                           value="{{$settings&&$settings->bot_settings?gmdate("i:s", $settings->bot_settings->bot_timeout):''}}">
                                </div>
                            </div>
                            <hr>
                            <h4>Rating Event</h4>
                            <div class="table-responsive">
                                <table class="table">
                                    @foreach($ratings as $key=>$rating)
                                        <tr>
                                            <td>{{$rating->description}}</td>
                                            <td>{{$rating->event}}</td>
                                            <td>
                                                <input class="form-control" type="number"
                                                       name="ratings[{{$rating->id}}]"
                                                       value="{{$rating->score}}">
                                            </td>
                                        </tr>
                                    @endforeach
                                </table>
                            </div>
                            <button class="btn btn-primary">Сохранить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection