api.poscare.ru/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'Admin\HomeController@index')->name('home');

    Route::prefix('user')->group(function () {
        /* HomeController. returns views */
        Route::get('/', 'Admin\HomeController@getUsers');
        Route::get('/get/{id}', 'Admin\HomeController@getUser');
        Route::get('/get/{user_id}/branch/new', 'Admin\HomeController@userBranchCreate');
        Route::get('/get/branch/{branch_id}/edit', 'Admin\HomeController@userBranchEdit');
        Route::get('/new', 'Admin\HomeController@newUser');
        Route::post('/new', 'Admin\HomeController@saveNewUser');
        /* AdminController. returns json */
        Route::post('/list', 'Admin\AdminController@userList');
        Route::post('/save', 'Admin\AdminController@saveUser');
        Route::post('/delete', 'Admin\AdminController@deleteUser');
        Route::post('/opt/create', 'Admin\AdminController@userOptCreate');
        Route::post('/opt/edit', 'Admin\AdminController@userOptEdit');
        Route::post('/branch/edit', 'Admin\AdminController@branchEdit');
        Route::post('/branch/create', 'Admin\AdminController@branchCreate');
        Route::post('/branch/image/add', 'Admin\AdminController@branchImageAdd');
        Route::post('/branch/image/delete', 'Admin\AdminController@branchImageDelete');
        Route::post('/branch/{branch_id}/delete', 'Admin\AdminController@userBranchDelete');
        Route::post('/service/verify', 'Admin\AdminController@userServiceVerify');


        Route::post('/rewards/force', 'Admin\RewardController@force');

    });
    Route::prefix('lists')->group(function () {
        // Route::get('/', 'Admin\AdminController@getLists');
        Route::get('/{vue_capture?}', function () {
            return view('lists');
        })->where('vue-capture', '[\/w\.-]*');
        Route::post('/categories', 'Admin\AdminController@getCategories');
        Route::post('/categories/order', 'Admin\AdminController@orderCategory');
        Route::post('/category/delete', 'Admin\AdminController@deleteCategory');
        Route::post('/category/create', 'Admin\AdminController@createCategory');
        Route::post('/category/edit', 'Admin\AdminController@editCategory');

        Route::post('/products', 'Admin\AdminController@getProducts');
        Route::post('/products/import', 'Admin\AdminController@importProducts');
        Route::get('/products/export', 'Admin\AdminController@exportProducts');
        Route::post('/products/order', 'Admin\AdminController@orderProducts');
        Route::post('/product/delete', 'Admin\AdminController@deleteProduct');
        Route::get('/product/create', 'Admin\AdminController@newProductPage');
        Route::post('/product/create', 'Admin\AdminController@newProduct');
        Route::get('/product/edit/{id}', 'Admin\AdminController@editProductPage');
        Route::post('/product/edit', 'Admin\AdminController@editProduct');

        Route::post('/services', 'Admin\AdminController@getServices');
        Route::post('/services/order', 'Admin\AdminController@orderServices');
        Route::get('/service/create', 'Admin\AdminController@createServicePage');
        Route::post('/service/create', 'Admin\AdminController@createService');
        Route::get('/service/edit/{id}', 'Admin\AdminController@editServicePage');
        Route::post('/service/edit', 'Admin\AdminController@editService');
        Route::post('/service/delete', 'Admin\AdminController@deleteService');

        Route::post('/characters', 'Admin\AdminController@getCharacters');
        Route::post('/characters/order', 'Admin\AdminController@orderCharacters');
        Route::post('/character/delete', 'Admin\AdminController@deleteCharacter');
        Route::post('/character/edit', 'Admin\AdminController@editCharacter');
        Route::post('/character/create', 'Admin\AdminController@createCharacter');

        Route::post('/related_services', 'Admin\AdminController@getRelatedServices');
        Route::post('/related_services/order', 'Admin\AdminController@orderRelatedServices');
        Route::post('/related_service/create', 'Admin\AdminController@createRelatedService');
        Route::post('/related_service/delete', 'Admin\AdminController@deleteRelatedService');
        Route::post('/related_service/edit', 'Admin\AdminController@editRelatedService');

        Route::post('/deliveries', 'Admin\AdminController@getDeliveries');
        Route::post('/deliveries/order', 'Admin\AdminController@orderDeliveries');
        Route::post('/delivery/delete', 'Admin\AdminController@deleteDelivery');
        Route::post('/delivery/edit', 'Admin\AdminController@editDelivery');
        Route::post('/delivery/create', 'Admin\AdminController@createDelivery');

        Route::post('/payments', 'Admin\AdminController@getPayments');
        Route::post('/payments/order', 'Admin\AdminController@orderPayments');
        Route::post('/payment/delete', 'Admin\AdminController@deletePayment');
        Route::post('/payment/edit', 'Admin\AdminController@editPayment');
        Route::post('/payment/create', 'Admin\AdminController@createPayment');

        Route::post('/rewards', 'Admin\RewardController@getRewards');
        Route::post('/reward/delete', 'Admin\RewardController@deleteReward');
        Route::get('/reward/edit/{id}', 'Admin\RewardController@editRewardPage');
        Route::post('/reward/edit', 'Admin\RewardController@editReward');
        Route::get('/reward/create', 'Admin\RewardController@createRewardPage');
        Route::post('/reward/create', 'Admin\RewardController@createReward');
    });
    Route::prefix('moderation')->group(function () {
        Route::get('/', 'Admin\AdminController@getModeration');

        Route::post('/bids', 'Admin\AdminController@bidsToModerate');
        Route::post('/bid/accept', 'Admin\AdminController@acceptBid');
        Route::post('/bid/reject', 'Admin\AdminController@rejectBid');
        Route::get('/bid/offer/{id}', 'Admin\AdminController@bidOfferPage');
        Route::post('/bid/offer', 'Admin\AdminController@bidOffer');

        Route::post('/orders', 'Admin\AdminController@ordersToModerate');
        Route::post('/order/accept', 'Admin\AdminController@acceptOrder');
        Route::post('/order/reject', 'Admin\AdminController@rejectOrder');
        Route::get('/order/offer/{id}', 'Admin\AdminController@orderOfferPage');
        Route::post('/order/offer', 'Admin\AdminController@orderOffer');

        Route::post('/reviews', 'Admin\AdminController@reviewsToModerate');
        Route::post('/review/accept', 'Admin\AdminController@acceptReview');
        Route::post('/review/reject', 'Admin\AdminController@rejectReview');

        Route::post('/images', 'Admin\AdminController@imagesToModerate');
        Route::post('/image/accept', 'Admin\AdminController@acceptImage');
        Route::post('/image/reject', 'Admin\AdminController@rejectImage');

	    Route::post('/tenders', 'Admin\TenderController@tendersToModerate');
	    Route::post('/tender/accept', 'Admin\TenderController@acceptTender');
	    Route::post('/tender/reject', 'Admin\TenderController@rejectTender');
    });
    Route::prefix('bids')->group(function () {
        Route::get('/', 'Admin\AdminController@getBidsPage');
        Route::post('/list', 'Admin\AdminController@getBids');
        Route::get('/new', 'Admin\AdminController@newBid');

        Route::get('/getOne/{id}', 'Admin\AdminController@getBid');
        Route::post('/getOne/edit', 'Admin\AdminController@editBid');
    });
    Route::prefix('orders')->group(function () {
        Route::get('/', 'Admin\AdminController@getOrdersPage');
        Route::post('/list', 'Admin\AdminController@getOrders');
        Route::get('/new', 'Admin\AdminController@newOrder');

        Route::get('/getOne/{id}', 'Admin\AdminController@getOrder');
        Route::post('/getOne/edit', 'Admin\AdminController@editOrder');
    });

    Route::prefix('tenders')->group(function () {
        Route::get('/', 'Admin\TenderController@list');
        Route::get('create', 'Admin\TenderController@create');
        Route::post('store', 'Admin\TenderController@store');
        Route::get('/{id}', 'Admin\TenderController@show');
        Route::get('{id}/edit', 'Admin\TenderController@edit');
        Route::post('update', 'Admin\TenderController@update');
        Route::post('delete', 'Admin\TenderController@delete');

        Route::prefix('response')->group(function () {
            //Route::get('list', 'Admin\TenderResponseController@list');
            //Route::get('show', 'Admin\TenderResponseController@show');
            //Route::post('create', 'Admin\TenderResponseController@create');
            //Route::post('edit', 'Admin\TenderResponseController@edit');
            Route::post('delete', 'Admin\TenderController@deleteResponse');
        });
    });

    Route::prefix('news')->group(function () {
        Route::get('/', 'Admin\AdminController@getNewsPage');
        Route::get('/get/{id}', 'Admin\AdminController@getNews');
        Route::get('/create', 'Admin\AdminController@createNewsPage');
        Route::post('/create', 'Admin\AdminController@createNews');
        Route::post('/edit', 'Admin\AdminController@editNews');
        Route::post('/delete', 'Admin\AdminController@deleteNews');
    });
    Route::prefix('sales')->group(function () {
        Route::get('/', 'Admin\AdminController@getSalesPage');
        Route::get('/get/{id}', 'Admin\AdminController@getSale');
        Route::get('/create', 'Admin\AdminController@createSalePage');

api.poscare.ru/app/Models/Bid.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Bid extends Model
{
    protected $table = 'bids';

    protected $guarded = ['id'];

    public function services()
    {
        return $this->belongsToMany('App\Models\Service',
            'bid_service',
            'bid_id',
            'service_id');
    }

    public function user()
    {

        return $this->belongsTo('App\Models\User');

    }

    public function product()
    {
        return $this->belongsTo('App\Models\Product','product_id');
    }

    public function bidResponses()
    {
        return $this->hasMany('App\Models\BidResponse','bid_id','id');
    }

    /**
     * Always capitalize the first name when we retrieve it
     */
    public function getCreatedAtAttribute($value) {
        return Carbon::parse($value)->timestamp;
    }
    /**
     * Always capitalize the first name when we retrieve it
     */
    public function getUpdatedAtAttribute($value) {
        return Carbon::parse($value)->timestamp;
    }

    /**
     * Always capitalize the first name when we retrieve it
     */
    public function getTermsAttribute($value) {
        return Carbon::parse($value)->timestamp;
    }
}

api.poscare.ru/resources/views/bid.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <ol class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li><a href="/bids">Заявки</a></li>
                    <li class="active">{{$bid->services->first()->name}}</li>
                </ol>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {{$bid->services->first()->name}}
                        <a class="pull-right btn btn-primary btn-xs" href="/moderation/bid/offer/{{$bid->id}}"> Сделать предложение </a>
                    </div>

                    <div class="panel-body" id="get-user">
                        <form action="/bids/getOne/edit" method="post">
                            {{ csrf_field() }}
                            <input type="hidden" name="id" value="{{$bid->id}}">
                            <div class="form-group">
                                <label for="product" class="control-label">Товар</label>
                                <select name="product_id" id="product" class="form-control">
                                    @foreach($products as $product)
                                        <option value="{{$product->id}}"
                                                @if($product->id==$bid->product_id) selected @endif>{{$product->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="service" class="control-label">Услуга</label>
                                <select name="service_id" id="service" class="form-control">
                                    @foreach($services as $service)
                                        <option value="{{$service->id}}"
                                                @if($bid->services()->find($service->id)) selected @endif>{{$service->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="description" class="control-label">Описание</label>
                                <input name="description" id="description" class="form-control"
                                       value="{{$bid->description}}">
                            </div>
                            <div class="form-group">
                                <label for="terms" class="control-label">Срок</label>
                                <input name="terms" id="terms" class="form-control"
                                       value="{{\Carbon\Carbon::createFromTimestamp($bid->terms)->format('Y-m-d H:i')}}">
                            </div>
                            <div class="form-group">
                                <label for="status" class="control-label">Статус</label>
                                <select name="status" id="status" class="form-control">
                                    <option value="0" @if($bid->status==0) selected @endif>Модерация</option>
                                    <option value="1" @if($bid->status==1) selected @endif>Новая</option>
                                    <option value="2" @if($bid->status==2) selected @endif>В работе</option>
                                    <option value="3" @if($bid->status==3) selected @endif>Выполнена</option>
                                    <option value="4" @if($bid->status==4) selected @endif>Заявка закреплена</option>
                                    <option value="5" @if($bid->status==5) selected @endif>В архиве</option>
                                </select>
                            </div>
                            <button class="btn btn-primary">Сохранить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

api.poscare.ru/resources/views/bidOffer.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <ol class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li><a href="/moderation">Модерация</a></li>
                    <li class="active">Новое предложение</li>
                </ol>
                <div class="panel panel-default">
                    <div class="panel-heading">Новое предложение</div>

                    <div class="panel-body" id="create-branch">
                        <form class="form-horizontal" method="post" action="/moderation/bid/offer" role="form">
                            {{ csrf_field() }}
                            <input type="hidden" name="bid_id" value="{{$bid->id}}">
                            <div class="form-group">
                                <label for="comment" class="col-sm-3 control-label">Комментарий</label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" id="comment" name="comment"
                                              placeholder="comment"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="quantity" class="col-sm-3 control-label">Срок</label>
                                <div class="col-sm-4">
                                    <input type="number" class="form-control" id="quantity" name="quantity"
                                           placeholder="Срок">
                                </div>
                                <div class="col-sm-4">
                                    <select class="form-control" id="quantity_type" name="quantity_type">
                                        <option value="1">часов</option>
                                        <option value="2">дней</option>
                                        <option value="3">месяцев</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label" for="price">Цена</label>
                                <div class="col-sm-8">
                                    <input class="form-control" type="text" name="price" id="price"/>
                                    @if ($errors->has('price'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label" for="branch">Филиал</label>
                                <div class="col-sm-8">
                                    <select class="form-control" id="branch" name="branch_id">
                                        @foreach($user->branches as $branch)
                                            <option value="{{$branch->id}}">{{$branch->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <hr>
                            <div class="col-sm-offset-3 checkbox">
                                <label class="control-label" for="private">
                                    <input type="checkbox" name="is_private" value="1" id="private">
                                    Скрыть от других пользователей
                                </label>
                            </div>
                            <button type="submit" class="btn btn-primary">Сделать предложение</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

api.poscare.ru/resources/views/createNews.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <ol class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li><a href="/news">Новости</a></li>
                    <li class="active">Создать новость</li>
                </ol>
                <div class="panel panel-default">
                    <div class="panel-heading">Создать новость</div>
                    <div class="panel-body">
                        <form action="/news/create" method="post" enctype="multipart/form-data">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label for="name">Название</label>
                                <input name="name" id="name" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="description">Текст</label>
                                <textarea name="description" id="description"
                                          class="form-control"></textarea>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-sm-3">Добавить изображение</label>
                                <div class="col-sm-8">
                                    <input type="file" multiple name="images[]">
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <hr>
                            <button type="submit" class="btn btn-primary">Сохранить данные</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

api.poscare.ru/resources/views/editBranch.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <ol class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li><a href="/user">Пользователи</a></li>
                    <li><a href="/user/get/{{$branch->user->id}}">{{$branch->user->name.' '.$branch->user->surname}}</a></li>
                    <li class="active">{{$branch->name}}</li>
                </ol>
                <div class="panel panel-default">
                    <div class="panel-heading">{{$branch->name}}</div>

                    <div class="panel-body" id="edit-branch">
                        <branch-edit :branch="{{$branch}}"></branch-edit>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

api.poscare.ru/resources/views/lists.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Справочник</div>

                    <div class="panel-body" id="vue-lists">
                        <lists></lists>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

api.poscare.ru/resources/views/newProduct.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <ol class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li><a href="/lists">Справочник</a></li>
                    <li class="active">Новый товар</li>
                </ol>
                <div class="panel panel-default">
                    <div class="panel-heading">Новый товар</div>

                    <div class="panel-body" id="create-branch">
                        <form class="form-horizontal" method="post" action="/lists/product/create" role="form" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="name" class="col-sm-3 control-label">Название</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="name" name="name" placeholder="name">
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="description" class="col-sm-3 control-label">Описание</label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" id="description" name="description"
                                              placeholder="description"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label" for="average_price">Среднаяя цена</label>
                                <div class="col-sm-8">
                                    <input class="form-control" type="text" name="average_price" id="average_price"/>
                                    @if ($errors->has('average_price'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('average_price') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label" for="category">Категория</label>
                                <div class="col-sm-8">
                                    <select class="form-control" name="category" id="category">
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}">{{$category->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Добавить изображение</label>
                                <div class="col-sm-8">
                                    <input type="file" multiple name="images[]">
                                </div>
                            </div>
                            <div class="col-sm-offset-3">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="is_actual" value="1">
                                        Актуален к продаже
                                    </label>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Сохранить данные</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

api.poscare.ru/resources/views/news.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <ol class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li class="active">Новости</li>
                </ol>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Новости
                        <a href="/news/create" class="pull-right btn btn-primary btn-xs">Добавить новость</a>
                    </div>

                    <div class="panel-body" id="get-orders">
                        @foreach($news_arr as $news)
                            <div class="media">
                                <a class="pull-left" href="/news/get/{{$news->id}}">
                                    <img class="media-object" src="{{$news->images->first()->href or '#'}}" alt="..."
                                         style=" max-width: 100px;">
                                </a>
                                <div class="media-body">
                                    <p>ID: <strong>{{$news->id}}</strong></p>
                                    <p>{{\Carbon\Carbon::createFromTimestamp($news->created_at)->format('d.m.Y H:i')}}</p>
                                    <h4 class="media-heading">
                                        <a href="/news/get/{{$news->id}}">
                                            {{$news->name}}
                                        </a>
                                    </h4>
                                    {{$news->description}}
                                </div>
                                <form action="/news/delete" method="post">
                                    {{csrf_field()}}
                                    <input type="hidden" name="news_id" value="{{$news->id}}">
                                    <button class="pull-right btn btn-danger btn-xs">Удалить</button>
                                </form>
                            </div>
                            <hr>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

api.poscare.ru/resources/views/orderNew.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <ol class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li><a href="/orders">Заказы</a></li>
                    <li class="active">Новый заказ</li>
                </ol>
                <div class="panel panel-default">
                    <div class="panel-heading">Создать заказ</div>

                    <div class="panel-body" id="get-user">
                        <form action="/orders/new" method="post">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label for="" class="control-label">

                                </label>
                                <input class="form-control" name="" id="">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

api.poscare.ru/resources/views/orders.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <ol class="breadcrumb">
                <li><a href="/">Главная</a></li>
                <li  class="active">Заказы</li>
            </ol>
            <div class="panel panel-default">
                <div class="panel-heading">Заказы</div>

                <div class="panel-body" id="get-orders">
                    <get-orders></get-orders>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection